const CAT_LABELS = {
  game:      "🎮 ゲーム",
  music:     "🎵 音楽",
  sports:    "💪 スポーツ",
  books:     "📚 読書",
  food:      "🍴 フード",
  lifestyle: "💚 ライフスタイル",
  creative:  "🎨 クリエイティブ",
  tools:     "🔧 ツール",
};

// Sorted by folder creation date (asc)
const PROJECTS = [
  {
    day: 1,  name: "Books That Appear",          dir: "appearing_book",
    desc: "一節から本と出会う本の探索サービス。気になるフレーズを入力すると関連する本を提案してくれる。",
    category: "books",     emoji: "📖", date: "2026-05-04",
    htmlFile: "index.html", tech: "html",
  },
  {
    day: 2,  name: "H!P MUSIC SELECTOR",         dir: "hello_project_recommend",
    desc: "ハロー！プロジェクトの楽曲をセレクトするレコメンダー。気分やシーンに合わせた曲を提案。",
    category: "music",     emoji: "🎤", date: "2026-05-04",
    htmlFile: "index.html", tech: "html",
  },
  {
    day: 3,  name: "変身 ─ りんご避けゲー",      dir: "shooting_metamorphosis",
    desc: "りんごを避けながら変身していくシューティング系ゲーム。避けるほどキャラが進化する。",
    category: "game",      emoji: "🎮", date: "2026-05-05",
    htmlFile: "metamorphosis_game.html", tech: "html",
  },
  {
    day: 4,  name: "唐揚げ or トイプードル",      dir: "karaage_poodle",
    desc: "唐揚げとトイプードルを見分けるクイズゲーム。似てるようで全然違う？",
    category: "game",      emoji: "🍗", date: "2026-05-06",
    htmlFile: "index.html", tech: "html",
  },
  {
    day: 5,  name: "Kindle おすすめ本ナビ",       dir: "kindle_recommend",
    desc: "Kindleのおすすめ本を案内するナビ。ジャンル・気分から読むべき一冊を見つける。",
    category: "books",     emoji: "📚", date: "2026-05-08",
    htmlFile: "kindle_recommender.html", tech: "html",
  },
  {
    day: 6,  name: "プロレス団体診断！",          dir: "wrestling_recommend",
    desc: "あなたの性格・好みからぴったりのプロレス団体を診断するアプリ。",
    category: "tools",     emoji: "🤼", date: "2026-05-08",
    htmlFile: "index.html", tech: "html",
  },
  {
    day: 7,  name: "OTSUKABE | 記録する",         dir: "bouldering_log",
    desc: "ボルダリングの記録をつけるログアプリ。課題・グレード・達成度を管理する。",
    category: "sports",    emoji: "📝", date: "2026-05-10",
    htmlFile: "index.html", tech: "html",
  },
  {
    day: 8,  name: "麻辣湯 具材提案ツール",       dir: "Malatang_prediction",
    desc: "麻辣湯（マーラータン）に入れる具材をAIが提案。好みの辛さや食材から最適な組み合わせを。",
    category: "food",      emoji: "🍲", date: "2026-05-10",
    htmlFile: "index.html", tech: "html",
  },
  {
    day: 9,  name: "名古屋 徒歩探索ルーレット", dir: "ino_tadataka_in_nagoya",
    desc: "伊能忠敬に倣い、大名古屋を自分の足で歩く。名古屋城・大須・熱田神宮などのコースをルーレットで選んで徒歩探索するアプリ。",
    category: "tools",     emoji: "🗾", date: "2026-05-11",
    htmlFile: "nagoya_walk_roulette.html", tech: "html",
  },
  {
    day: 10, name: "トークネタカード",             dir: "random_card_talk",
    desc: "ランダムにトークネタが出てくるカードアプリ。会話のきっかけに。",
    category: "tools",     emoji: "💬", date: "2026-05-11",
    htmlFile: "index.html", tech: "html",
  },
  {
    day: 11, name: "どうぶつインディアンポーカー", dir: "indian_poker_animal",
    desc: "動物キャラで遊ぶインディアンポーカー。かわいいビジュアルでカードゲームを楽しむ。",
    category: "game",      emoji: "🃏", date: "2026-05-12",
    htmlFile: "index.html", tech: "html",
  },
  {
    day: 12, name: "東海道新幹線 遅延通知",        dir: "line_shinkansen_delay",
    desc: "東海道新幹線（東京〜名古屋間）に遅延が発生したとき、LINEに自動通知するシステム。GitHub Actions + LINE API で動作。",
    category: "tools",     emoji: "🚄", date: "2026-05-13",
    htmlFile: null, tech: "system",
  },
  {
    day: 13, name: "TOURNAMENT MAKER",             dir: "make_tournament",
    desc: "かんたんトーナメント表作成ツール。参加者を入力するだけで即座にトーナメント表を生成。",
    category: "game",      emoji: "🏆", date: "2026-05-13",
    htmlFile: "tournament.html", tech: "html",
  },
  {
    day: 14, name: "ArtBubble",                    dir: "art_bubble",
    desc: "アートを泡のように楽しむビジュアル体験。インタラクティブなアートアプリ。",
    category: "creative",  emoji: "🫧", date: "2026-05-16",
    htmlFile: "index.html", tech: "html",
  },
  {
    day: 15, name: "RAP BATTLE DOJO",              dir: "rap_practice",
    desc: "ラップバトル練習アプリ。AIとフリースタイルで対戦しながらリリック力を磨く。",
    category: "music",     emoji: "🎙️", date: "2026-05-16",
    htmlFile: null, tech: "nextjs",
  },
  {
    day: 16, name: "DANCE LENS",                   dir: "dance_practice",
    desc: "ダンス動画を解析してフィードバックするアプリ。フォームチェックや改善点をAIが提案。",
    category: "creative",  emoji: "💃", date: "2026-05-17",
    htmlFile: null, tech: "nextjs",
  },
  {
    day: 17, name: "Pawlog | ペットの一行日記",    dir: "pet_log",
    desc: "ペットの日々を一行で記録する日記アプリ。シンプルに続けられるペット記録。",
    category: "lifestyle", emoji: "🐾", date: "2026-05-17",
    htmlFile: null, tech: "nextjs",
  },
  {
    day: 18, name: "TRAINING RECOMMEND",           dir: "training_recommend",
    desc: "あなたの目標・体力・環境に合ったトレーニングメニューを提案するアプリ。",
    category: "sports",    emoji: "💪", date: "2026-05-19",
    htmlFile: "index.html", tech: "html",
  },
  {
    day: 19, name: "元気アクション！",             dir: "genki_action",
    desc: "モチベーションを上げるアクションカード。やる気が出ないときにシャッフルして一枚引く。",
    category: "lifestyle", emoji: "⚡", date: "2026-05-19",
    htmlFile: "index.html", tech: "html",
  },
  {
    day: 20, name: "ストーリー作成",               dir: "story_generator",
    desc: "Instagramストーリーで何かを募集したい時の画像をサクッと作れるジェネレーター。テキスト・スタンプ・背景を選んで即出力。",
    category: "creative",  emoji: "✍️", date: "2026-05-21",
    htmlFile: "index.html", tech: "html",
  },
  {
    day: 21, name: "めし＆ストック",               dir: "health_tracker",
    desc: "食事記録と冷蔵庫の在庫管理が同時にできるアプリ。何を食べたかと何が残っているかを一括管理。",
    category: "lifestyle", emoji: "💚", date: "2026-05-21",
    htmlFile: "index.html", tech: "html",
  },
  {
    day: 22, name: "コーデ提案",                   dir: "outfit_advisor",
    desc: "AIがコーディネートを提案するアドバイザー。手持ちの服や天気、気分から今日のコーデを提案。",
    category: "lifestyle", emoji: "👗", date: "2026-05-23",
    htmlFile: "index.html", tech: "html",
  },
  {
    day: 23, name: "ボルダリングAIコーチ",         dir: "bouldering",
    desc: "AIがボルダリングをコーチングしてくれるアプリ。課題の攻略法や練習メニューをアドバイス。",
    category: "sports",    emoji: "🧗", date: "2026-05-23",
    htmlFile: null, tech: "html",
  },
  {
    day: 24, name: "チワワ or ブルーベリーマフィン", dir: null,
    desc: "チワワとブルーベリーマフィンを見分けるクイズゲーム。唐揚げ or トイプードルに続く「区別できる？」シリーズ第2弾。",
    category: "game",      emoji: "🐶", date: "2026-05-24",
    htmlFile: null, tech: "googleai",
    tweetUrl: "https://x.com/asukaokochi/status/2058430525132743135",
  },
  {
    day: 25, name: "😃 増殖クリッカー",            dir: "smile_clicker",
    desc: "笑顔が増殖するクリッカーゲーム。クリックするほど笑顔が画面を埋め尽くしていく。",
    category: "game",      emoji: "😃", date: "2026-05-25",
    htmlFile: "index.html", tech: "html",
  },
  {
    day: 26, name: "BPM Finder",                   dir: "bpm_finder",
    desc: "指定のBPMの曲を教えてくれるツール。ランニングにちょうど良いのはBPM130くらいなんだって。",
    category: "music",     emoji: "🎵", date: "2026-05-26",
    htmlFile: "index.html", tech: "html",
  },
  {
    day: 27, name: "おすすめのお酒診断",           dir: "drink_diagnosis",
    desc: "あなたにぴったりのお酒を診断するアプリ。気分・シーン・好みを入力して今夜の一杯を決める。",
    category: "food",      emoji: "🍻", date: "2026-05-27",
    htmlFile: "index.html", tech: "html",
  },
  {
    day: 28, name: "にゃんこ通知",                 dir: "cat-reminder",
    desc: "猫の投薬・通院・ケアのタイミングを教えてくれるリマインダー。大切な子のお世話を忘れずに。",
    category: "lifestyle", emoji: "🐱", date: "2026-05-29",
    htmlFile: "index.html", tech: "html",
  },
  {
    day: 29, name: "ボルダリング体験会ナビ",       dir: "bouldering_events",
    desc: "名古屋のボルダリング体験会情報まとめサイト。初心者向け体験会のスケジュールをまとめて確認。",
    category: "sports",    emoji: "📍", date: "2026-05-29",
    htmlFile: null, tech: "html",
  },
  {
    day: 30, name: "30 Days of Building with Claude", dir: null,
    desc: "30日間・29プロダクトを作り続けた記録をまとめたポートフォリオサイト。このサイト自体が30日目の作品。",
    category: "creative",  emoji: "🎉", date: "2026-06-04",
    htmlFile: "index.html", tech: "html",
  },
];
